<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Image extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Image_model');
        $this->load->model('Product_model');
    } 

    /*
     * Listing of images
     */
    function index()
    {
        $data['images'] = $this->Image_model->get_all_images();

        $this->load->view('image/index',$data);
    }

    /*
     * Adding a new image
     */
    function add()
    {   

        $data['products'] = $this->Product_model->show_packet();
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name' => $this->input->post('name'),
				'P_id' => $this->input->post('P_id'),
            );
            
            $image_id = $this->Image_model->add_image($params);
            redirect('image/index');
        }
        else
        {
            
            $this->load->view('image/add',$data);
        }
    }  

    /*
     * Editing a image
     */
    function edit($id)
    {   
        // check if the image exists before trying to edit it
        $image = $this->Image_model->get_image($id);
        
        if(isset($image['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name' => $this->input->post('name'),
					'P_id' => $this->input->post('P_id'),
                );

                $this->Image_model->update_image($id,$params);            
                redirect('image/index');
            }
            else
            {   
                $data['image'] = $this->Image_model->get_image($id);
    
                $this->load->view('image/edit',$data);
            }
        }
        else
            show_error('The image you are trying to edit does not exist.');
    } 

    /*
     * Deleting image
     */
    function remove($id)
    {
        $image = $this->Image_model->get_image($id);

        // check if the image exists before trying to delete it
        if(isset($image['id']))
        {
            $this->Image_model->delete_image($id);
            redirect('image/index');
        }
        else
            show_error('The image you are trying to delete does not exist.');
    }
    
}
