<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Order extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Order_model');
    } 

    /*
     * Listing of orders
     */
    function index()
    {
        $data['orders'] = $this->Order_model->get_all_orders();
        require 'template/back/header.php';
        $this->load->view('order/index',$data);
    }

    /*
     * Adding a new order
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'order_date' => date('Y-m-d H:i:s'),
				'total' => $this->input->post('total'),
				'user_id' => $this->input->post('user_id'),
				'fullname' => $this->input->post('fullname'),
				'email' => $this->input->post('email'),
				'phone' => $this->input->post('phone'),
				'address' => $this->input->post('address'),
				'district' => $this->input->post('district'),
				'province' => $this->input->post('province'),
				'postcode' => $this->input->post('postcode'),
				'order_status' => $this->input->post('order_status'),
            );
            
            $order_id = $this->Order_model->add_order($params);

            redirect('order/index');
        }
        else
        {
            require 'template/back/header.php';
            $this->load->view('order/add');
        }
    }  

    /*
     * Editing a order
     */
    function edit($id)
    {   
        // check if the order exists before trying to edit it
        $order = $this->Order_model->get_order($id);
        
        if(isset($order['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'order_date' => date('Y-m-d H:i:s'),
					'total' => $this->input->post('total'),
					'user_id' => $this->input->post('user_id'),
					'fullname' => $this->input->post('fullname'),
					'email' => $this->input->post('email'),
					'phone' => $this->input->post('phone'),
					'address' => $this->input->post('address'),
					'district' => $this->input->post('district'),
					'province' => $this->input->post('province'),
					'postcode' => $this->input->post('postcode'),
					'order_status' => $this->input->post('order_status'),
                );

                $this->Order_model->update_order($id,$params);            
                redirect('order/index');
            }
            else
            {   
                $data['order'] = $this->Order_model->get_order($id);
                require 'template/back/header.php';
                $this->load->view('order/edit',$data);
            }
        }
        else
            show_error('The order you are trying to edit does not exist.');
    } 

    /*
     * Deleting order
     */
    function remove($id)
    {
        $order = $this->Order_model->get_order($id);

        // check if the order exists before trying to delete it
        if(isset($order['id']))
        {
            $this->Order_model->delete_order($id);
            redirect('order/index');
        }
        else
            show_error('The order you are trying to delete does not exist.');
    }
    
}
