<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Order_detail extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Order_detail_model');
    } 

    /*
     * Listing of order_details
     */
    function index()
    {
        $data['order_details'] = $this->Order_detail_model->get_all_order_details();

        $this->load->view('order_detail/index',$data);
    }

    /*
     * Adding a new order_detail
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'quantity' => $this->input->post('quantity'),
				'price' => $this->input->post('price'),
            );
            
            $order_detail_id = $this->Order_detail_model->add_order_detail($params);
            redirect('order_detail/index');
        }
        else
        {
            $this->load->view('order_detail/add');
        }
    }  

    /*
     * Editing a order_detail
     */
    function edit($order_id)
    {   
        // check if the order_detail exists before trying to edit it
        $order_detail = $this->Order_detail_model->get_order_detail($order_id);
        
        if(isset($order_detail['order_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'quantity' => $this->input->post('quantity'),
					'price' => $this->input->post('price'),
                );

                $this->Order_detail_model->update_order_detail($order_id,$params);            
                redirect('order_detail/index');
            }
            else
            {   
                $data['order_detail'] = $this->Order_detail_model->get_order_detail($order_id);
    
                $this->load->view('order_detail/edit',$data);
            }
        }
        else
            show_error('The order_detail you are trying to edit does not exist.');
    } 

    /*
     * Deleting order_detail
     */
    function remove($order_id)
    {
        $order_detail = $this->Order_detail_model->get_order_detail($order_id);

        // check if the order_detail exists before trying to delete it
        if(isset($order_detail['order_id']))
        {
            $this->Order_detail_model->delete_order_detail($order_id);
            redirect('order_detail/index');
        }
        else
            show_error('The order_detail you are trying to delete does not exist.');
    }
    
}
