<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Payment extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Payment_model');
    } 

    /*
     * Listing of payments
     */
    function index()
    {
        $data['payments'] = $this->Payment_model->get_all_payments();

        $this->load->view('payment/index',$data);
    }

    /*
     * Adding a new payment
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'pay_money' => $this->input->post('pay_money'),
				'pay_date' => $this->input->post('pay_date'),
				'detail' => $this->input->post('detail'),
				'order_id' => $this->input->post('order_id'),
            );
            
            $payment_id = $this->Payment_model->add_payment($params);
            redirect('payment/index');
        }
        else
        {
            $this->load->view('payment/add');
        }
    }  

    /*
     * Editing a payment
     */
    function edit($id)
    {   
        // check if the payment exists before trying to edit it
        $payment = $this->Payment_model->get_payment($id);
        
        if(isset($payment['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'pay_money' => $this->input->post('pay_money'),
					'pay_date' => $this->input->post('pay_date'),
					'detail' => $this->input->post('detail'),
					'order_id' => $this->input->post('order_id'),
                );

                $this->Payment_model->update_payment($id,$params);            
                redirect('payment/index');
            }
            else
            {   
                $data['payment'] = $this->Payment_model->get_payment($id);
    
                $this->load->view('payment/edit',$data);
            }
        }
        else
            show_error('The payment you are trying to edit does not exist.');
    } 

    /*
     * Deleting payment
     */
    function remove($id)
    {
        $payment = $this->Payment_model->get_payment($id);

        // check if the payment exists before trying to delete it
        if(isset($payment['id']))
        {
            $this->Payment_model->delete_payment($id);
            redirect('payment/index');
        }
        else
            show_error('The payment you are trying to delete does not exist.');
    }
    
}
