<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Product_category extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Product_category_model');
    } 

    /*
     * Listing of product_categories
     */
    function index()
    {
        
        $data['product_categories'] = $this->Product_category_model->get_all_product_categories();
        require 'template/back/header.php';
        $this->load->view('product_category/index',$data);
    }

    /*
     * Adding a new product_category
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'codename' => $this->input->post('codename'),
				'name' => $this->input->post('name'),
				'created' => date('Y-m-d H:i:s'),
            );
            
            $product_category_id = $this->Product_category_model->add_product_category($params);
            redirect('product_category/index');
        }
        else
        {
            require 'template/back/header.php';
            $this->load->view('product_category/add');
        }
    }  

    /*
     * Editing a product_category
     */
    function edit($id)
    {   
        // check if the product_category exists before trying to edit it
        $product_category = $this->Product_category_model->get_product_category($id);
        
        if(isset($product_category['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'codename' => $this->input->post('codename'),
					'name' => $this->input->post('name'),
					'created' => date('Y-m-d H:i:s'),
                );

                $this->Product_category_model->update_product_category($id,$params);            
                redirect('product_category/index');
            }
            else
            {   

                $data['product_category'] = $this->Product_category_model->get_product_category($id);
                require 'template/back/header.php';
                $this->load->view('product_category/edit',$data);
            }
        }
        else
            show_error('The product_category you are trying to edit does not exist.');
    } 

    /*
     * Deleting product_category
     */
    function remove($id)
    {
        $product_category = $this->Product_category_model->get_product_category($id);

        // check if the product_category exists before trying to delete it
        if(isset($product_category['id']))
        {
            $this->Product_category_model->delete_product_category($id);
            redirect('product_category/index');
        }
        else
            show_error('The product_category you are trying to delete does not exist.');
    }
    
}
