<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class User extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        
        $this->load->helper('form');
        $this->load->library('form_validation');

        $this->load->model('Product_model');
        $this->load->model('User_model');
        $this->load->model('Product_category_model');
        $this->load->model('Order_model');
        
    } 

    //Login
    function login()
    {

        $this->form_validation->set_rules('username', 'Username', 'required|alpha_numeric');
        $this->form_validation->set_rules('password', 'Password', 'required');


        if ($this->form_validation->run() == false) 
            {
                
                
                $this->load->view('user/login');
            } else 
                {
            
                    // set variables from the form
                    $username = $this->input->post('username');
                    $password = $this->input->post('password');
            
                    $user_id        = $this->User_model->get_user_id($username);           
                    $user_username  = $this->User_model->get_user_username($username);
                    $user_password  = $this->User_model->get_user_password($username);
                    $user_type      = $this->User_model->get_user_user_type($username);

                    $cid        = (int)$user_id;                         
                    $cusername  = (string)$user_username;
                    $cpassword  = (string)$user_password;
                    $cuser_type = (string)$user_type; 


                                            if($username == $cusername&&$password == $cpassword)
                                                {// set session user datas
                                                    
                
                                                    $_SESSION['user_id']      = $cid;
                                                    $_SESSION['username']     = $cusername;
                                                    $_SESSION['user_type']    = $user_type;
                                                    
                                                    //$user_id            = $this->User_model->get_user_id($username);
                                                    $user_username      = $this->User_model->get_user_username($username); 
                                                    $data['User']       = $this->User_model->getRows();
                                                    $data['Category']   = $this->Product_category_model->getRows();
                                                    $data['Product']    = $this->Product_model->getRows();
                                                    $data['Order']      = $this->Order_model->getRows();

                            
                
                                                    //$id_user['user_id']    = $this->User_model->get_user_id($username); 
                                                    // user login ok
                                                    $title = 'login ok';
                                                    require 'template/back/header.php';
                                                    $this->load->view('back/index',$data);
                                                }else
                                                    {
                                                        $this->load->view('user/login');
                                                    }
                                        


                            
                
                        
            
                }

    }//Login

    //Logout
    function logout()
    {
        unset($_SESSION['user_id'] );
        unset($_SESSION['username'] );
        unset($_SESSION['user_type']);

        $this->load->view('user/login');
    }//Logout


    /*
     * Listing of users
     */
    function list()
    {
        $data['users'] = $this->User_model->get_all_users();
        require 'template/back/header.php';
        $this->load->view('user/index',$data);

        
    }
    function index()
    {
        //$data['users'] = $this->User_model->get_all_users();

        //$this->load->view('user/index',$data);

        $this->load->view('user/login');
    }
    function home()
    {
        //$data['users'] = $this->User_model->get_all_users();

        //$this->load->view('user/index',$data);
        $data['User']       = $this->User_model->getRows();
        $data['Category']   = $this->Product_category_model->getRows();
        $data['Product']    = $this->Product_model->getRows();
        $data['Order']      = $this->Order_model->getRows();
        require 'template/back/header.php';
        $this->load->view('back/index',$data);
    }
    function back_packet()
    {
        $data['category'] = $this->Product_category_model->get_all_product_categories();
        $data['products'] = $this->Product_model->get_all_products();
        require 'template/back/header.php';
        $this->load->view('back/packet',$data);
    }

    function users()
    {
        $data['users'] = $this->User_model->get_all_users();
        //require 'template/back/header.php';
        $this->load->view('user/main',$data);

        
    }

    /*
     * Adding a new user
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'firstname' => $this->input->post('firstname'),
				'lastname' => $this->input->post('lastname'),
				'username' => $this->input->post('username'),
				'password' => $this->input->post('password'),
				'email' => $this->input->post('email'),
				'phone' => $this->input->post('phone'),
				'address' => $this->input->post('address'),
				'district' => $this->input->post('district'),
				'province' => $this->input->post('province'),
				'postcode' => $this->input->post('postcode'),
				'created' => $this->input->post('created'),
				'user_type' => $this->input->post('user_type'),
            );
            

            $user_id = $this->User_model->add_user($params);
            redirect('user/index');
        }
        else
        {
            require 'template/back/header.php';
            $this->load->view('user/add');
        }
    }  

    /*
     * Editing a user
     */
    function edit($id)
    {   
        // check if the user exists before trying to edit it
        $user = $this->User_model->get_user($id);
        
        if(isset($user['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'firstname' => $this->input->post('firstname'),
					'lastname' => $this->input->post('lastname'),
					'username' => $this->input->post('username'),
					'password' => $this->input->post('password'),
					'email' => $this->input->post('email'),
					'phone' => $this->input->post('phone'),
					'address' => $this->input->post('address'),
					'district' => $this->input->post('district'),
					'province' => $this->input->post('province'),
					'postcode' => $this->input->post('postcode'),
					'created' => date('Y-m-d H:i:s'),
					'user_type' => $this->input->post('user_type'),
                );

                $this->User_model->update_user($id,$params);            
                redirect('user/index');
            }
            else
            {   
                $data['user'] = $this->User_model->get_user($id);
                require 'template/back/header.php';
                $this->load->view('user/edit',$data);
            }
        }
        else
            show_error('The user you are trying to edit does not exist.');
    } 

    /*
     * Deleting user
     */
    function remove($id)
    {
        $user = $this->User_model->get_user($id);

        // check if the user exists before trying to delete it
        if(isset($user['id']))
        {
            $this->User_model->delete_user($id);
            redirect('user/index');
        }
        else
            show_error('The user you are trying to delete does not exist.');
    }
    
}
