<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Image_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get image by id
     */
    function get_image($id)
    {
        $image = $this->db->query("
            SELECT
                *

            FROM
                `images`

            WHERE
                `id` = ?
        ",array($id))->row_array();

        return $image;
    }
    
    /*
     * Get all images
     */
    function get_all_images()
    {
        $images = $this->db->query("
            SELECT
                *

            FROM
                `images`

            WHERE
                1 = 1
        ")->result_array();

        return $images;
    }
    
    /*
     * function to add new image
     */
    function add_image($params)
    {
        $this->db->insert('images',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update image
     */
    function update_image($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('images',$params);
        if($response)
        {
            return "image updated successfully";
        }
        else
        {
            return "Error occuring while updating image";
        }
    }
    
    /*
     * function to delete image
     */
    function delete_image($id)
    {
        $response = $this->db->delete('images',array('id'=>$id));
        if($response)
        {
            return "image deleted successfully";
        }
        else
        {
            return "Error occuring while deleting image";
        }
    }
}
