<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Order_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function getRows()
    {
        $rs=$this->db->get("orders");

        return $rs->num_rows();
    }
    
    /*
     * Get order by id
     */
    function get_order($id)
    {
        return $this->db->get_where('orders',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all orders
     */
    function get_all_orders()
    {
        return $this->db->get('orders')->result_array();
    }
    
    /*
     * function to add new order
     */
    function add_order($params)
    {
        $this->db->insert('orders',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update order
     */
    function update_order($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('orders',$params);
        if($response)
        {
            return "order updated successfully";
        }
        else
        {
            return "Error occuring while updating order";
        }
    }
    
    /*
     * function to delete order
     */
    function delete_order($id)
    {
        $response = $this->db->delete('orders',array('id'=>$id));
        if($response)
        {
            return "order deleted successfully";
        }
        else
        {
            return "Error occuring while deleting order";
        }
    }
}
