<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Order_detail_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get order_detail by order_id
     */
    function get_order_detail($order_id)
    {
        return $this->db->get_where('order_details',array('order_id'=>$order_id))->row_array();
    }
    
    /*
     * Get all order_details
     */
    function get_all_order_details()
    {
        return $this->db->get('order_details')->result_array();
    }
    
    /*
     * function to add new order_detail
     */
    function add_order_detail($params)
    {
        $this->db->insert('order_details',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update order_detail
     */
    function update_order_detail($order_id,$params)
    {
        $this->db->where('order_id',$order_id);
        $response = $this->db->update('order_details',$params);
        if($response)
        {
            return "order_detail updated successfully";
        }
        else
        {
            return "Error occuring while updating order_detail";
        }
    }
    
    /*
     * function to delete order_detail
     */
    function delete_order_detail($order_id)
    {
        $response = $this->db->delete('order_details',array('order_id'=>$order_id));
        if($response)
        {
            return "order_detail deleted successfully";
        }
        else
        {
            return "Error occuring while deleting order_detail";
        }
    }
}
