<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Payment_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get payment by id
     */
    function get_payment($id)
    {
        return $this->db->get_where('payments',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all payments
     */
    function get_all_payments()
    {
        return $this->db->get('payments')->result_array();
    }
    
    /*
     * function to add new payment
     */
    function add_payment($params)
    {
        $this->db->insert('payments',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update payment
     */
    function update_payment($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('payments',$params);
        if($response)
        {
            return "payment updated successfully";
        }
        else
        {
            return "Error occuring while updating payment";
        }
    }
    
    /*
     * function to delete payment
     */
    function delete_payment($id)
    {
        $response = $this->db->delete('payments',array('id'=>$id));
        if($response)
        {
            return "payment deleted successfully";
        }
        else
        {
            return "Error occuring while deleting payment";
        }
    }
}
