<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Product_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function getRows()
    {
        $rs=$this->db->get("products");

        return $rs->num_rows();
    }
	//	àÃÕÂ¡´Ùá¾ç¤à¡¨
	function view($id)
    {	
		
		$sql_pd = "SELECT p.*, c.name as cname, c.id as cid FROM products p ";
		$sql_pd .= "INNER JOIN product_categories c ";
		$sql_pd .= "ON p.product_categorie_id=c.id ";
		$sql_pd .= "WHERE p.id=$id ";
		
		
		return  $this->db->query($sql_pd)->result_array();
        // return $this->db->get('query_pc')->result_array();
    }
	//	àÃÕÂ¡á¾ç¤à¡¨â´ÂËÁÇ´ËÁÙè
	function view_categories($cid)
    {	
		

		$sql_pc = "SELECT p.id, p.name as pname, p.price , p.image, c.name as cname ";
		$sql_pc .= "FROM products p INNER JOIN product_categories c ON p.product_categorie_id = c.id ";
		$sql_pc .= "WHERE p.product_categorie_id=$cid ";
		
		return  $this->db->query($sql_pc)->result_array();
        // return $this->db->get('query_pc')->result_array();
    }
	//	àÃÕÂ¡á¾ç¤à¡¨â´ÂËÁÇ´ËÁÙè
	function show_categories($id)
    {	
		

		$sql_pc = "SELECT p.id, p.name as pname, p.price , p.image, c.name as cname ";
		$sql_pc .= "FROM products p INNER JOIN product_categories c ON p.product_categorie_id = c.id ";
		$sql_pc .= "WHERE p.product_categorie_id=$id ";
		
		return  $this->db->query($sql_pc)->result_array();
        // return $this->db->get('query_pc')->result_array();
    }
	//	àÃÕÂ¡á¾ç¤à¡¨·Ñé§ËÁ´
	function show_packet()
    {	
		

		$sql_pc = "SELECT p.id, p.name as pname, p.price , p.image, c.name as cname ";
		$sql_pc .= "FROM products p INNER JOIN product_categories c ON p.product_categorie_id = c.id ";
		return  $this->db->query($sql_pc)->result_array();
        // return $this->db->get('query_pc')->result_array();
    }
    
    /*
     * Get product by id
     */
    function get_product($id)
    {
        return $this->db->get_where('products',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all products
     */
    function get_all_products()
    {
        return $this->db->get('products')->result_array();
    }
    
    /*
     * function to add new product
     */
    function add_product($params)
    {
        $this->db->insert('products',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update product
     */
    function update_product($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('products',$params);
        if($response)
        {
            return "product updated successfully";
        }
        else
        {
            return "Error occuring while updating product";
        }
    }
    
    /*
     * function to delete product
     */
    function delete_product($id)
    {
        $response = $this->db->delete('products',array('id'=>$id));
        if($response)
        {
            return "product deleted successfully";
        }
        else
        {
            return "Error occuring while deleting product";
        }
    }
}
