<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class User_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function getRows()
    {
        $rs=$this->db->get("users");

        return $rs->num_rows();
    }
    function get_user_username($username) {
        
        $this->db->select('username');
        $this->db->from('users');
        $this->db->where('username', $username);

        return $this->db->get()->row('username');
        
    }
    function get_user_password($username) {
        
        $this->db->select('password');
        $this->db->from('users');
        $this->db->where('username', $username);

        return $this->db->get()->row('password');
        
    }
    function get_user_user_type($username) {
        
        $this->db->select('user_type');
        $this->db->from('users');
        $this->db->where('username', $username);

        return $this->db->get()->row('user_type');
        
    }
    function get_user_id($username) {
        
        $this->db->select('id');
        $this->db->from('users');
        $this->db->where('username', $username);

        return $this->db->get()->row('id');
        
    }
    /*
     * Get user by id
     */
    function get_user($id)
    {
        return $this->db->get_where('users',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all users
     */
    function get_all_users()
    {
        return $this->db->get('users')->result_array();
    }
    
    /*
     * function to add new user
     */
    function add_user($params)
    {
        $this->db->insert('users',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user
     */
    function update_user($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('users',$params);
        if($response)
        {
            return "user updated successfully";
        }
        else
        {
            return "Error occuring while updating user";
        }
    }
    
    /*
     * function to delete user
     */
    function delete_user($id)
    {
        $response = $this->db->delete('users',array('id'=>$id));
        if($response)
        {
            return "user deleted successfully";
        }
        else
        {
            return "Error occuring while deleting user";
        }
    }
}
